name: emailSeguro15day
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://www.orozcorp.live/api/emailSeguro15day' \
          --header 'Authorization: Bearer ${{ secrets.CRON_KEY }}'
